In [1]:
import torch 

In [11]:
x = torch.arange(4.0)
print(x)

tensor([0., 1., 2., 3.])


In [12]:
x.requires_grad_(True) # 等价于 x = torch.arange(5.0, requires_grad=True)
# x.grad # 默认值是None
print(x.grad)

None


In [13]:
# 函数定义：y是x的函数
y = 2 * torch.dot(x, x)
# 此时使用反向传播，就会自动计算在y函数上，x的梯度
print(y)

tensor(28., grad_fn=<MulBackward0>)


In [14]:
# 接下来，通过调用反向传播函数来自动计算y关于x每个分量的梯度
y.backward() # y对x求导
x.grad

tensor([ 0.,  4.,  8., 12.])

In [17]:
# y=XTX的梯度是2X，可以快速来验证
print(4*x == x.grad)

tensor([True, True, True, True])


In [ ]:
# 计算另一个函数的梯度的时候，梯度需要先清零
x.grad.zero_()

# 使用另一个函数，注意函数y的结果需要是标量
y = torch.sum(x)
y.backward()
print(x.grad)

tensor([1., 1., 1., 1.])


In [19]:
# 在默认情况下，PyTorch会累积梯度，我们需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1., 1.])

In [ ]:
# 非标量变量的反向传播
# 对非标量调用backward需要传入一个 gradient 参数，该参数指定微分函数关于self的梯度。
x.grad.zero_()
print(x)
# 按元素乘积
y = x * x

# 传入 gradient 参数，本例只想求偏导数的和，所以传递一个1的梯度是合适的
# The graph is differentiated using the chain rule. If the tensor is non-scalar (i.e. its data has more than one element) and requires gradient, 
# the function additionally requires specifying a gradient. 
# It should be a tensor of matching type and shape, that represents the gradient of the differentiated function w.r.t.
y.backward(torch.ones(len(x)))
print(x.grad)
print('---------')
print(torch.ones(len(x)))

tensor([0., 1., 2., 3.], requires_grad=True)
tensor([0., 2., 4., 6.])
---------
tensor([1., 1., 1., 1.])


好的，我们来深入解析一下你提供的这段关于 PyTorch/TensorFlow 自动微分机制的描述，这有助于你更好地理解深度学习框架中的反向传播原理。  

---

## 核心概念：`Tensor` 求导与 `gradient` 参数

在 PyTorch 等框架中，当对一个 **非标量 Tensor**（即形状不是 `()` 的张量，例如向量、矩阵、高维张量）调用 `.backward()` 时，需要显式传入一个 `gradient` 参数，这个参数的形状必须和原张量完全一致。

### 为什么需要 `gradient`？

我们可以从数学和工程实现两个角度来理解这件事。

#### 1. 数学角度：链式法则的多维度扩展

在微积分中，我们习惯计算**标量**对**向量**的导数（这会得到一个梯度向量），或者**向量**对**向量**的导数（这会得到一个雅可比矩阵）。

- 当你有一个标量损失函数 `L` 时，计算 `dL/dx`（`x` 是模型参数）是直观的，结果是一个与 `x` 同形的向量/张量。
- 但如果你有一个**非标量张量** `y`（比如一个 `(batch_size, num_classes)` 的输出），直接计算 `dy/dx` 会得到一个非常庞大的**雅可比矩阵**（或更高阶的张量），这在计算上是低效且不必要的。

**深度学习的最终目标是优化一个标量损失**（例如，整个批次的平均分类损失）。因此，框架不会直接计算 `dy/dx`，而是计算：
$$
\frac{dL}{dx} = \sum_{i} \frac{dL}{y_i} \cdot \frac{dy_i}{dx}
$$
这里的 $\frac{dL}{y_i}$ 就是你需要传入的 `gradient`，它代表了**上游梯度**（来自损失函数对当前张量 `y` 的每个元素的导数）。

#### 2. 工程角度：高效的反向传播实现

框架在设计时，为了避免存储和计算巨大的雅可比矩阵，采用了**反向累积**（backward accumulation）的策略。

- 在正向传播时，框架会记录计算图（每个操作的输入、输出和导数公式）。
- 在反向传播时，从标量损失 `L` 开始，计算 `dL/dy`（这是 `y` 的梯度），然后将这个梯度作为 `gradient` 参数传给 `y.backward()`，框架再根据链式法则计算出 `y` 的每个依赖项的梯度（例如 `x` 的梯度）。

### 代码示例

假设你有一个简单的计算图：
```python
import torch

# 定义变量
x = torch.tensor([1.0, 2.0], requires_grad=True)
y = x ** 2  # y = [1.0, 4.0]
```

如果你直接对 `y` 调用 `.backward()`，会报错：
```python
y.backward()  # 报错：RuntimeError: grad can be implicitly created only for scalar outputs
```

这是因为 `y` 是一个向量，框架不知道你要计算哪个标量对 `x` 的梯度。这时你需要传入一个 `gradient`：
```python
# 假设我们的损失函数对 y 的梯度是 [1.0, 1.0]
gradient = torch.tensor([1.0, 1.0])
y.backward(gradient)

# 打印 x 的梯度
print(x.grad)  # 输出: tensor([2., 4.])
```

这个结果是怎么来的？
- `y = x^2`，所以 `dy/dx = 2x`。
- 传入的 `gradient` 是 `[1.0, 1.0]`，代表 `dL/dy = [1.0, 1.0]`。
- 根据链式法则，`dL/dx = dL/dy * dy/dx = [1.0*2*1.0, 1.0*2*2.0] = [2.0, 4.0]`。

### 常见应用场景
1. **多输出模型**：例如一个模型同时输出分类结果和回归结果，你需要为每个输出指定权重，然后将它们的梯度组合起来作为 `gradient`。
2. **自定义损失函数**：当你实现一个复杂的损失函数时，可能需要手动计算损失对模型输出的梯度，然后将其传入 `.backward()`。
3. **中间层梯度计算**：在某些情况下，你可能需要计算中间层张量对输入的梯度，这时候也需要手动指定 `gradient`。

### 总结
- 对**标量**调用 `.backward()` 时，框架会自动计算梯度。
- 对**非标量张量**调用 `.backward()` 时，需要传入一个 `gradient` 参数，它代表了**上游梯度**（损失函数对当前张量的导数）。
- 这个机制是链式法则在多维度下的高效实现，避免了直接计算庞大的雅可比矩阵。

---

以下这句话不太理解
当y不是标量时，向量y关于向量x的导数的最自然解释是一个矩阵。 对于高阶和高维的y和x，求导的结果可以是一个高阶张量。

然而，虽然这些更奇特的对象确实出现在高级机器学习中（包括深度学习中）， 但当调用向量的反向计算时，我们通常会试图计算一批训练样本中每个组成部分的损失函数的导数。 这里，我们的目的不是计算微分矩阵，而是单独计算批量中每个样本的偏导数之和。

-------- 
好的，我们来试着拆解一下这段话，我会用一些通俗的例子来帮助理解。

这段话的核心意思是：**在机器学习，特别是深度学习的反向传播中，我们计算的梯度（导数）并不是严格意义上的数学矩阵或张量，而是一个简化后的、更实用的向量。**

我们分两部分来理解：

### 第一部分：数学上的定义

> 当y不是标量时，向量y关于向量x的导数的最自然解释是一个矩阵。对于高阶和高维的y和x，求导的结果可以是一个高阶张量。

这部分是纯粹的数学概念。让我们用具体的例子来说明。

1.  **标量对向量的导数 (最常见的情况)**
    - **场景**: 假设你有一个标量损失函数 `L` (比如，模型预测的误差)，它取决于一个向量 `x` (比如，模型的权重 `w1, w2, w3`)。
    - **求导**: 我们想知道 `L` 分别对 `x` 的每一个分量的变化率是多少。
    - **结果**: 导数 `dL/dx` 会是一个和 `x` 维度相同的向量。这个向量就叫做**梯度 (Gradient)**。
    - **例子**:
        - $`L = 2 * w1 + 3 * w2^2 - w3`$
        - $`x = [w1, w2, w3]`$
        - $`dL/dx = [dL/dw1, dL/dw2, dL/dw3] = [2, 6*w2, -1]`$
    - **结论**: 标量对向量的导数是一个**向量**。这是我们在优化算法（如梯度下降）中最常处理的对象。

2.  **向量对向量的导数 (雅可比矩阵 Jacobian Matrix)**
    - **场景**: 现在假设 `y` 不是一个标量，而是一个向量。比如，`y` 是一个有3个输出的神经网络层的输出 `[y1, y2, y3]`，而 `x` 是一个有2个输入的向量 `[x1, x2]`。
    - **求导**: 我们想知道 `y` 的每一个分量 (`y1`, `y2`, `y3`) 分别对 `x` 的每一个分量 (`x1`, `x2`) 的变化率。
    - **结果**: 这会形成一个 **矩阵**。这个矩阵就叫做**雅可比矩阵**。它的行数等于 `y` 的维度，列数等于 `x` 的维度。
    - **例子**:
        - `y1 = x1 + x2`
        - `y2 = x1 * x2`
        - `y = [y1, y2]`
        - `x = [x1, x2]`
        - 雅可比矩阵 `dy/dx` 就是：
          ```
          [ dy1/dx1, dy1/dx2 ]   =   [ 1, 1 ]
          [ dy2/dx1, dy2/dx2 ]       [ x2, x1 ]
          ```
    - **结论**: 向量对向量的导数是一个**矩阵**。

3.  **张量对张量的导数 (高阶张量)**
    - **场景**: 如果 `y` 和 `x` 都是更高维度的张量（比如，一个2x2的矩阵），那么求导的结果会是一个更高阶的张量。
    - **结论**: 数学上，导数的阶数等于 `y` 的阶数加上 `x` 的阶数。例如，一个2阶张量（矩阵）对一个2阶张量的导数是一个4阶张量。

### 第二部分：机器学习中的实际应用

> 然而，虽然这些更奇特的对象确实出现在高级机器学习中（包括深度学习中），但当调用向量的反向计算时，我们通常会试图计算一批训练样本中每个组成部分的损失函数的导数。这里，我们的目的不是计算微分矩阵，而是单独计算批量中每个样本的偏导数之和。

这部分解释了为什么在实际编程中，我们感觉不到在处理复杂的矩阵或张量。

1.  **我们的目标是计算“梯度”，而不是“雅可比矩阵”**
    - 在深度学习中，我们的最终目标几乎总是最小化一个**标量损失函数** `L` (例如，整个批次的平均损失)。
    - 因此，我们最关心的是**标量 `L` 相对于模型中每一个参数 `w` 的梯度 `dL/dw`**。
    - 即使中间层的输出是向量或张量，在反向传播的最后一步，我们也会将其“聚合”或“降维”到一个标量损失上，然后再求导。

2.  **批量处理 (Batch Processing) 的影响**
    - 现代深度学习框架（如TensorFlow/PyTorch）为了效率，都是**批量**处理数据的。假设我们一次处理 `N` 个样本。
    - **前向传播**: 一个批次的输入 `X` (形状为 `N x ...`) 经过网络，得到一个批次的预测 `Y_pred` (形状为 `N x ...`)。
    - **计算损失**: 我们将批次预测 `Y_pred` 与真实标签 `Y_true` 比较，计算出一个**标量损失** `L`。这个 `L` 通常是 `N` 个样本各自损失的平均值或总和。
    - **反向传播**: 当我们调用 `L.backward()` 时，框架需要计算的是 `dL/dw`，即**整个批次的总损失**相对于每个模型参数 `w` 的梯度。

3.  **“偏导数之和”的含义**
    - 这句话是理解的关键。对于每个模型参数 `w`：
        - 样本1的损失 `L_1` 对 `w` 的偏导数是 `dL_1/dw`。
        - 样本2的损失 `L_2` 对 `w` 的偏导数是 `dL_2/dw`。
        - ...
        - 样本N的损失 `L_N` 对 `w` 的偏导数是 `dL_N/dw`。
    - 总损失 `L = (L_1 + L_2 + ... + L_N) / N` (假设是平均损失)。
    - 那么，总梯度 `dL/dw = (dL_1/dw + dL_2/dw + ... + dL_N/dw) / N`。
    - 这正是框架在后台为每个参数所做的计算：**它计算了批量中每个样本引起的梯度，然后将它们加起来（并除以批量大小）**。

### 总结

| 场景 | 数学对象 | 机器学习中的实际操作 | 目的 |
| :--- | :--- | :--- | :--- |
| **单个样本** | 标量损失 `L` 对向量参数 `w` 的导数是一个**向量** (梯度)。 | 计算该样本损失的梯度。 | 为了更新参数，减少该样本的损失。 |
| **一批样本** | 向量损失 `[L_1, L_2, ...]` 对向量参数 `w` 的导数是一个**矩阵** (雅可比)。 | **不直接计算雅可比矩阵**。而是计算每个样本损失的梯度向量，然后将它们**相加**（并归一化）。 | 为了更新参数，减少**整个批次**的平均损失，这比单个样本更新更稳定、更高效。 |

所以，你在代码中看到的 `grad` 变量，它的形状和模型参数 `w` 完全一样，是一个向量（或张量），而不是一个更大的矩阵。这是因为框架已经帮你完成了对整个批次样本梯度的求和操作，让你可以方便地进行参数更新。

In [ ]:
# 分离计算
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x
print(u)

z.sum().backward()
print(x.grad == u)

tensor([0., 1., 4., 9.])
tensor([True, True, True, True])


In [31]:
x.grad.zero_()
y = x * x
print(y)
u = y * x 
u.backward(torch.ones(len(x)))
print(x.grad)

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)
tensor([ 0.,  3., 12., 27.])


In [33]:
x.grad.zero_()
y = x.dot(x)
y.sum().backward()
print(x.grad == 2 * x)

tensor([True, True, True, True])


In [ ]:
# Python控制流的梯度计算，使用自动微分的一个好处是： 即使构建函数的计算图需要通过Python控制流
# （例如，条件、循环或任意函数调用），我们仍然可以计算得到的变量的梯度。 在下面的代码中，while循环的迭代次数和if语句的结果都取决于输入a的值。
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

# 随机生成一个标量，符合正态分布
print(torch.randn(size=()))
# 随机生成1个1行2列的矩阵，矩阵元素符合正态分布
print(torch.randn(size=(1,2)))
# 随机生成一个矩阵，矩阵元素符合正泰分布
print(torch.randn((1,2,3)))
a = torch.randn(size=(), requires_grad=True)
print('----------')
print(a)
d = f(a)
d.backward()

# 计算a的范数
a.norm()

tensor(-0.7968)
tensor([[ 1.7635, -1.6772]])
tensor([[[-0.5678,  0.2272,  0.7853],
         [-1.1240,  0.8044, -1.0012]]])
----------
tensor(0.1532, requires_grad=True)


我们来详细探讨一下 `tensor.norm()` 这个方法。`tensor.norm()` 是 PyTorch 中用于计算张量（Tensor）范数（Norm）的函数，**范数是衡量张量“大小”或“距离”的一种数学工具**，在机器学习、深度学习中应用广泛（如正则化、梯度裁剪、距离计算等）。

### 一、基本概念：什么是范数？

范数是向量/张量空间中一个函数，满足以下性质：
1. **非负性**：`||x|| ≥ 0`，且仅当 `x = 0` 时 `||x|| = 0`；
2. **齐次性**：`||kx|| = |k|·||x||`（`k` 为常数）；
3. **三角不等式**：`||x + y|| ≤ ||x|| + ||y||`。

常见的范数类型：
- **Lₚ 范数**：`||x||ₚ = (Σ|xᵢ|ᵖ)^(1/p)`（`p ≥ 1`，`xᵢ` 是张量的元素）；
  - `p=1`：L₁ 范数（曼哈顿距离），`||x||₁ = Σ|xᵢ|`；
  - `p=2`：L₂ 范数（欧几里得距离），`||x||₂ = √(Σxᵢ²)`（最常用）；
  - `p=∞`：无穷范数（切比雪夫距离），`||x||∞ = max(|xᵢ|)`。
- **Frobenius 范数（矩阵范数）**：`||A||_F = √(ΣΣAᵢⱼ²)`（对矩阵/高维张量，等价于将所有元素展平后的 L₂ 范数）。


### 二、`tensor.norm()` 的语法与参数

PyTorch 中 `tensor.norm()` 的核心语法：
```python
torch.norm(input, p='fro', dim=None, keepdim=False, out=None, dtype=None)
```
或张量实例方法：
```python
input.norm(p='fro', dim=None, keepdim=False, out=None, dtype=None)
```

#### 关键参数解析：
1. **`input`**：输入张量（必须是浮点型或复数型，整数型需先转换）；
2. **`p`**：范数类型（默认 `'fro'`，即 Frobenius 范数）：
   - 整数/浮点数：指定 Lₚ 范数的 `p`（如 `p=1`、`p=2`、`p=0.5`）；
   - `'fro'`：Frobenius 范数（仅对 2 维及以上张量有效，等价于展平后 L₂ 范数）；
   - `'nuc'`：核范数（仅对 2 维张量有效，即奇异值之和）；
   - `float('inf')`：无穷范数（`max(|xᵢ|)`）；
   - `float('-inf')`：负无穷范数（`min(|xᵢ|)`）。
3. **`dim`**：指定计算范数的维度（默认 `None`，即对整个张量计算范数，返回标量）：
   - 例：`dim=0`（按第 0 维计算，返回该维度上的范数向量）；
   - 多维：`dim=(0,1)`（按第 0+1 维联合计算）。
4. **`keepdim`**：是否保留计算维度（默认 `False`，即压缩该维度）；
5. **`out`**：输出张量（可选，用于节省内存）；
6. **`dtype`**：输出数据类型（可选，默认与输入一致）。


### 三、常用示例（覆盖核心场景）

假设输入张量：
```python
import torch

x = torch.tensor([[1.0, -2.0], [3.0, 4.0]])  # 2x2 浮点张量
```

#### 1. 对整个张量计算范数（默认 `dim=None`）
- **L₂ 范数（`p=2`）**：
  ```python
  print(x.norm(p=2))  # 输出：tensor(5.4772)
  # 计算过程：√(1² + (-2)² + 3² + 4²) = √(1+4+9+16) = √30 ≈5.4772
  ```
- **L₁ 范数（`p=1`）**：
  ```python
  print(x.norm(p=1))  # 输出：tensor(10.)
  # 计算过程：|1| + |-2| + |3| + |4| = 1+2+3+4=10
  ```
- **Frobenius 范数（`p='fro'`）**：
  ```python
  print(x.norm(p='fro'))  # 输出：tensor(5.4772)
  # 等价于 L₂ 范数（2 维张量的 Frobenius 范数 = 展平后 L₂ 范数）
  ```
- **无穷范数（`p=float('inf')`）**：
  ```python
  print(x.norm(p=float('inf')))  # 输出：tensor(4.)
  # 计算过程：max(|1|, |-2|, |3|, |4|) =4
  ```

#### 2. 按指定维度计算范数（`dim` 参数）
- **按行计算 L₂ 范数（`dim=1`）**：
  ```python
  # 每行的 L₂ 范数：√(1²+(-2)²) ≈2.236，√(3²+4²)=5
  print(x.norm(p=2, dim=1))  # 输出：tensor([2.2361, 5.0000])
  ```
- **按列计算 L₁ 范数（`dim=0`）**：
  ```python
  # 每列的 L₁ 范数：|1|+|3|=4，|-2|+|4|=6
  print(x.norm(p=1, dim=0))  # 输出：tensor([4., 6.])
  ```
- **保留维度（`keepdim=True`）**：
  ```python
  # 按行计算，保留 2 维结构（原形状 2x2 → 2x1）
  print(x.norm(p=2, dim=1, keepdim=True))
  # 输出：
  # tensor([[2.2361],
  #         [5.0000]])
  ```

#### 3. 高维张量的范数计算
假设 3 维张量（形状：`2x2x2`）：
```python
y = torch.tensor([[[1.0, 2.0], [3.0, 4.0]], [[5.0, 6.0], [7.0, 8.0]]])
```
- 按 `dim=2`（第 2 维）计算 L₂ 范数：
  ```python
  # 每个 2x1 向量的 L₂ 范数：√(1²+2²)≈2.236，√(3²+4²)=5，√(5²+6²)≈7.81，√(7²+8²)≈10.63
  print(y.norm(p=2, dim=2))
  # 输出：
  # tensor([[2.2361, 5.0000],
  #         [7.8102, 10.6301]])
  ```
- 按 `dim=(0,1)`（第 0+1 维联合）计算 Frobenius 范数：
  ```python
  # 对每个 2x2 子张量计算 Frobenius 范数：√(1²+2²+3²+4²)=√30≈5.477，√(5²+...+8²)=√174≈13.19
  print(y.norm(p='fro', dim=(0,1)))
  # 输出：tensor([5.4772, 13.1909])
  ```

#### 4. 复数张量的范数
`norm()` 对复数张量计算的是“模长范数”（实部² + 虚部² 的平方根）：
```python
z = torch.tensor([1.0 + 2.0j, 3.0 - 4.0j])  # 复数张量
print(z.norm(p=2))  # 输出：tensor(5.4772)
# 计算过程：√(|1+2j|² + |3-4j|²) = √((1+4)+(9+16)) = √30≈5.4772
```


### 四、注意事项
1. **数据类型限制**：`norm()` 仅支持浮点型（`float32`、`float64`）和复数型（`complex64`、`complex128`）张量，整数型张量需先转换（如 `x.float().norm()`）；
2. **`p` 的取值范围**：Lₚ 范数要求 `p ≥ 1`（`p=0` 不是严格意义上的范数，PyTorch 中 `p=0` 会计算非零元素个数的平方根）；
3. **核范数（`p='nuc'`）**：仅对 2 维张量有效（矩阵），计算奇异值之和（如 `x.norm(p='nuc')`）；
4. **梯度计算**：`norm()` 是可微分的，支持自动求导（如在深度学习中用于正则化项时，会自动计算梯度）。


### 五、常见应用场景
1. **正则化**：在损失函数中添加 L₁/L₂ 范数（如权重衰减），防止模型过拟合；
   ```python
   # 假设 model 是一个神经网络，对权重参数加 L₂ 正则化
   l2_reg = 0.01
   for param in model.parameters():
       l2_reg += param.norm(p=2)
   loss = original_loss + l2_reg  # 总损失 = 原始损失 + 正则化项
   ```
2. **梯度裁剪**：限制梯度的 L₂ 范数，防止梯度爆炸（如在 RNN、Transformer 中）；
   ```python
   torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)  # 基于 norm() 实现
   ```
3. **距离计算**：计算两个张量的 L₂ 距离（如在聚类、检索任务中）；
   ```python
   a = torch.tensor([1.0, 2.0])
   b = torch.tensor([3.0, 4.0])
   distance = (a - b).norm(p=2)  # 等价于 torch.norm(a - b, p=2)
   ```
4. **张量归一化**：将张量按范数归一化到单位长度（如 `x / x.norm(p=2)`）。


### 总结

`tensor.norm()` 是 PyTorch 中计算张量范数的核心工具，支持多种范数类型（Lₚ、Frobenius、核范数等）和灵活的维度指定，是机器学习中正则化、梯度控制、距离计算的基础。使用时需注意数据类型、`p` 的取值及 `dim` 的设置，根据具体场景选择合适的范数类型。

In [50]:
# 我们现在可以分析上面定义的f函数。 请注意，它在其输入a中是分段线性的。 
# 换言之，对于任何a，存在某个常量标量k，使得f(a)=k*a，其中k的值取决于输入a，因此可以用d/a验证梯度是否正确。
print(a.grad)
a.grad == d / a

tensor(8192.)


tensor(True)

In [62]:
import math
x = torch.tensor([float(1),float(2),float(3)])
print(x)
print(x.norm(p=2.0))
print(math.sqrt(1 + 2**2 + 3**2))

tensor([1., 2., 3.])
tensor(3.7417)
3.7416573867739413
