In [ ]:
import torch

# 标量
X = torch.tensor(3.5) # 创建一个标量张量
Y = torch.tensor(4)
X + Y # 结果也是一个标量张量

tensor(7.5000)

In [7]:
# 一维张量表示向量
x = torch.tensor([11,12,14,15,16,10]) # 0到11的整数序列，步长为1，结果是一个一维张量
# x[3] # 第i个索引元素
x[3:7] # 切片操作，索引从0开始，包括3但不包括7

tensor([15, 16, 10])

In [ ]:
# 长度
len(x) # 张量的长度
# 向量或轴的维度被用来表示向量或轴的长度，即向量或轴的元素数量。 然而，张量的维度用来表示张量具有的轴数。 在这个意义上，张量的某个轴的维数就是这个轴的长度
x.shape # 张量的形状

torch.Size([6])

In [11]:
X = torch.arange(12).reshape(3,4)
X.T # 矩阵转置

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

In [12]:
# 对称矩阵（symmetric matrix）等于其转置
A = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [13]:
# 张量（本小节中的“张量”指代数对象）是描述具有任意数量轴的维数组的通用方法
X = torch.arange(24).reshape(2, 3, 4)
X[1] # 取出第1个矩阵，索引从0开始


tensor([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])

In [14]:
# 张量运算
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [15]:
A * B #两个矩阵的按元素乘法称为Hadamard积

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [17]:
# 将张量乘以或加上一个标量不会改变张量的形状，其中张量的每个元素都将与标量相加或相乘。
A + 2,A * 3

(tensor([[ 2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9.],
         [10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.]]),
 tensor([[ 0.,  3.,  6.,  9.],
         [12., 15., 18., 21.],
         [24., 27., 30., 33.],
         [36., 39., 42., 45.],
         [48., 51., 54., 57.]]))

In [ ]:
# 降维
# 求和
# A.sum() # 所有元素求和

# 按行或按列求和
A.sum(axis=0), A.sum(axis=1) # axis=0表示按列，axis=1表示按行，此时变为一维张量
A.sum(axis=0).shape

A.sum(axis=0, keepdim=True) # 保持二维张量的形状不变
# A.sum(axis=1, keepdim=True).shape  


torch.Size([5, 1])

In [27]:
# 
# A.sum(axis=[0,1]) # 沿着行和列求和，等价于A.sum()，结果是一个标量

# 平均值
# A.mean(), A.sum()/A.numel() # A.numel()返回张量中元素的数量

# 指定轴方向计算平均值
A,A.mean(axis=0), A.mean(axis=1, keepdim=True) # keepdim=True保持二维张量的形状不变

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 1.5000],
         [ 5.5000],
         [ 9.5000],
         [13.5000],
         [17.5000]]))

In [29]:
# 非降维求和,有时在调用函数来计算总和或均值时保持轴数不变会很有用
A.sum(axis=1, keepdim=True)


tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [34]:
A,A.sum(axis=1, keepdim=True),A/A.sum(axis=1, keepdim=True),A.mean(axis=0, keepdim=True)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]),
 tensor([[0.0000, 0.1667, 0.3333, 0.5000],
         [0.1818, 0.2273, 0.2727, 0.3182],
         [0.2105, 0.2368, 0.2632, 0.2895],
         [0.2222, 0.2407, 0.2593, 0.2778],
         [0.2286, 0.2429, 0.2571, 0.2714]]),
 tensor([[ 8.,  9., 10., 11.]]))

In [ ]:
# 沿某个轴计算A元素的累积总和
A,A.cumsum(axis=0) # 沿着轴0累加

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  6.,  8., 10.],
         [12., 15., 18., 21.],
         [24., 28., 32., 36.],
         [40., 45., 50., 55.]]))

In [45]:
# 向量点积，结果是一个标量
y = torch.ones(4, dtype=torch.float32)
y,y.shape,y.T,y.T.shape,y.dot(y)

# 等价于
y.dot(y), (y * y).sum(), y.T @ y


(tensor(4.), tensor(4.), tensor(4.))

In [55]:
# 矩阵-向量积
x = torch.arange(4, dtype=torch.float32)
A.shape,x.shape,torch.mv(A, x) # mv表示matrix-vecotrtor

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [60]:
# 矩阵乘法
B = torch.ones(4, 3)
A.shape, B.shape, torch.mm(A, B) # mm表示matrix-matrix

(torch.Size([5, 4]),
 torch.Size([4, 3]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]))

In [ ]:
# 向量范数
u = torch.tensor([3.0, -4.0])
u.norm() # L2范数
torch.abs(u).sum() # L1范数，等价于 u.norm(1)

tensor(7.)

In [ ]:
# 矩阵范数，L2范数矩阵元素平方和的平方根，目标，或许是深度学习算法最重要的组成部分（除了数据），通常被表达为范数
A.norm() # L2范数

tensor(49.6991)