In [2]:
import torch

In [3]:
# 标量，由只有一个元素的张量表示，可以进行类似算术运算的张量计算
X = torch.tensor(3.5) # 创建一个标量张量
Y = torch.tensor(4)
print(X + Y,X**Y) # 结果也是一个标量张量

tensor(7.5000) tensor(150.0625)


In [7]:
# 一维张量表示向量，大量文献认为列向量是向量的默认方向
x = torch.tensor([11,12,14,15,16,10]) # 0到11的整数序列，步长为1，结果是一个一维张量
print(x[3]) # 第i个索引元素
print(x[3:7]) # 切片操作，索引从0开始，包括3但不包括7，如果后索引超过张量长度，则取到最后一个元素

tensor(15)
tensor([15, 16, 10])


In [ ]:
# 向量的长度，维数和形状
len(x) # 张量的长度
# 向量或轴的维度被用来表示向量或轴的长度，即向量或轴的元素数量。 然而，张量的维度用来表示张量具有的轴数。 在这个意义上，张量的某个轴的维数就是这个轴的长度
# 形状（shape）是一个元素组，列出了张量沿每个轴的长度（维数）。 对于只有一个轴的张量，形状只有一个元素。
x.shape # 张量的形状

torch.Size([6])

In [ ]:
# 矩阵，即二维张量
X = torch.arange(12).reshape(3,4)
X.T # 矩阵转置

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

In [10]:
# 对称矩阵（symmetric matrix）等于其转置
A = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [12]:
# 张量是矩阵的推广，向量是一阶张量，矩阵是二阶张量
# 张量（本小节中的“张量”指代数对象）是描述具有任意数量轴的维数组的通用方法
X = torch.arange(24).reshape(2, 3, 4)
print(X)
print(X[1]) # 取出第1个矩阵，索引从0开始


tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])


In [18]:
# 张量运算
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
print(id(A), id(B))  # id函数用于查看变量的内存地址，确保A和B不是同一个对象
print(A,'\n',B)
# 张量按元素相加
print(A + B)

4382647760 5216665040
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) 
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])


In [19]:
A * B #两个矩阵的按元素乘法称为Hadamard积

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [17]:
# 将张量乘以或加上一个标量不会改变张量的形状，其中张量的每个元素都将与标量相加或相乘。
A + 2,A * 3

(tensor([[ 2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9.],
         [10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.]]),
 tensor([[ 0.,  3.,  6.,  9.],
         [12., 15., 18., 21.],
         [24., 27., 30., 33.],
         [36., 39., 42., 45.],
         [48., 51., 54., 57.]]))

In [ ]:
# 降维
# 求和
print(A)
# 默认情况下，调用求和函数会沿所有的轴降低张量的维度，使它变为一个标量
print(A.sum()) # 所有元素求和
print(A.shape)
# 按行或按列求和
print(A.sum(axis=0), A.sum(axis=1)) # axis=0表示按列，axis=1表示按行，此时变为一维张量
print(A.sum(axis=0).shape)
print(A.sum(axis=1).shape)


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor(190.)
torch.Size([5, 4])
tensor([40., 45., 50., 55.]) tensor([ 6., 22., 38., 54., 70.])
torch.Size([4])
torch.Size([5])
tensor([[40., 45., 50., 55.]])


In [30]:
# 保持形状，即不降维
print(A.sum(axis=0, keepdim=True)) # 保持二维张量的形状不变
print(A.sum(axis=0, keepdim=True).shape) # 保持二维张量的形状不变
print(A.sum(axis=1, keepdim=True))

tensor([[40., 45., 50., 55.]])
torch.Size([1, 4])
tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])


In [27]:
# 
# A.sum(axis=[0,1]) # 沿着行和列求和，等价于A.sum()，结果是一个标量

# 平均值
# A.mean(), A.sum()/A.numel() # A.numel()返回张量中元素的数量

# 指定轴方向计算平均值
A,A.mean(axis=0), A.mean(axis=1, keepdim=True) # keepdim=True保持二维张量的形状不变

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 1.5000],
         [ 5.5000],
         [ 9.5000],
         [13.5000],
         [17.5000]]))

In [ ]:
# 非降维求和,有时在调用函数来计算总和或均值时保持轴数不变会很有用
A.sum(axis=1, keepdim=True)

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [34]:
A,A.sum(axis=1, keepdim=True),A/A.sum(axis=1, keepdim=True),A.mean(axis=0, keepdim=True)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]),
 tensor([[0.0000, 0.1667, 0.3333, 0.5000],
         [0.1818, 0.2273, 0.2727, 0.3182],
         [0.2105, 0.2368, 0.2632, 0.2895],
         [0.2222, 0.2407, 0.2593, 0.2778],
         [0.2286, 0.2429, 0.2571, 0.2714]]),
 tensor([[ 8.,  9., 10., 11.]]))

In [ ]:
# 沿某个轴计算A元素的累积总和
A,A.cumsum(axis=0) # 沿着轴0累加

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  6.,  8., 10.],
         [12., 15., 18., 21.],
         [24., 28., 32., 36.],
         [40., 45., 50., 55.]]))

In [ ]:
# 向量点积，结果是一个标量，实际值为 x.T * y
y = torch.ones(6, dtype=torch.float32)
y,y.shape,x.T,y.T,y.dot(y)

# x * y # 按元素乘法

# y.dot(x) 等价于(适用于向量)
# y.dot(y), (y * y).sum(), y.T @ y

(tensor(6.), tensor(6.), tensor(6.))

In [ ]:
# 矩阵-向量 积
x = torch.arange(4, dtype=torch.float32)
A.shape,x.shape,torch.mv(A, x) # mv表示matrix-vecotrtor

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [31]:
# 矩阵乘法
B = torch.ones(4, 3)
A.shape, B.shape, torch.mm(A, B) # mm表示matrix-matrix

(torch.Size([5, 4]),
 torch.Size([4, 3]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]))

In [32]:
# 向量范数
u = torch.tensor([3.0, -4.0])
u.norm() # L2范数
torch.abs(u).sum() # L1范数，等价于 u.norm(1)

tensor(7.)

In [ ]:
# 矩阵范数，L2范数矩阵元素平方和的平方根，目标，或许是深度学习算法最重要的组成部分（除了数据），通常被表达为范数
A.norm() # L2范数

tensor(49.6991)

In [33]:
A = torch.arange(20,dtype=float).reshape(5, 4)
A,A.mean(),A.mean(axis=0),A.mean(axis=1, keepdim=True)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]], dtype=torch.float64),
 tensor(9.5000, dtype=torch.float64),
 tensor([ 8.,  9., 10., 11.], dtype=torch.float64),
 tensor([[ 1.5000],
         [ 5.5000],
         [ 9.5000],
         [13.5000],
         [17.5000]], dtype=torch.float64))