In [ ]:
!uv pip install torch

In [5]:
import torch # 首先，我们导入torch。请注意，虽然它被称为PyTorch，但是代码中使用torch而不是pytorch。

# 指定类型
x = torch.arange(12, dtype=torch.float32)  # 创建一个包含12个连续整数的张量，并将其数据类型指定为float32
print(x.shape)  # 查看张量的形状
print(x.reshape(3, 4))  # 将张量重新形状为3行4列的矩阵并打印出来
print(x.reshape(3, 4).shape)  # 查看重新形状后的张量的形状
print(x.reshape(3, 4).dtype)  # 查看重新形状后的张量的数据类型

torch.Size([12])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
torch.Size([3, 4])
torch.float32


In [ ]:
# 使用 arange 创建一个行向量 
x = torch.arange(12)  # [0, 1, ..., 11]

# 可以通过张量的shape属性来访问张量（沿每个轴的长度）的形状
x.shape # torch.Size([12])

# 张量中元素的总数，即形状的所有元素的乘积
x.numel() # 12

# 改变一个张量的形状而不改变元素数量和元素值，可以调用reshape函数
y = x.reshape(3, 4) # 3行4列的矩阵
y.shape # torch.Size([3, 4])

# 可以通过-1来调用此自动计算出维度的功能。 即我们可以用x.reshape(-1,4)或x.reshape(3,-1)来取代x.reshape(3,4)
x.reshape(-1, 4) # torch.Size([3, 4]) # -1 则表示自动计算该维度
x.reshape(2, -1) # torch.Size([2, 6])

In [ ]:
y = x.reshape((1,2,3,2)) # torch.Size([1, 2, 3, 2])
y.shape

torch.Size([1, 2, 3, 2])

In [ ]:


# 零填充初始张量
torch.zeros((2, 3, 4)) # 2个3行4列的矩阵，元素全是零

torch.ones((2, 3, 4)) # 2个3行4列的矩阵，元素全是1

torch.randn(3, 4) # 3行4列的矩阵，元素服从标准正态分布

torch.tensor([[1, 2, 3], [4, 5, 6]]) # 2行3列的矩阵，元素为指定值

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# 按元素运算，对应元素之间进行逐元素运算
x = torch.tensor([1.0, 2, 4, 8]) # 创建一个张量
y = torch.tensor([2.0, 2, 2, 2]) #
x + y, x - y, x * y, x / y, x ** y # 张量的逐元素加、减、乘、除和幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [ ]:
# e为底的指数运算
torch.exp(x) # 指数运算

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [10]:
# 矩阵拼接
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[1, 0, 1, 0], [0, 1, 0, 1], [1, 0, 1, 0]], dtype=torch.float32)
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1) # 在第0维（行）和第1维（列）上分别拼接矩阵X和Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 1.,  0.,  1.,  0.],
         [ 0.,  1.,  0.,  1.],
         [ 1.,  0.,  1.,  0.]]),
 tensor([[ 0.,  1.,  2.,  3.,  1.,  0.,  1.,  0.],
         [ 4.,  5.,  6.,  7.,  0.,  1.,  0.,  1.],
         [ 8.,  9., 10., 11.,  1.,  0.,  1.,  0.]]))

In [11]:
# 通过逻辑运算符构建二元张量
X < 5, X == Y # 逐元素比较X和Y的值

(tensor([[ True,  True,  True,  True],
         [ True, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [12]:
X.sum() # 所有元素求和，产出一个单元素张量

tensor(66.)

In [13]:
# 广播机制
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [ ]:
# 广播机制是自动完成的
a + b # a和b的维度并不相同，但仍然可以相加，因为PyTorch会自动地将它们扩展成相同的形状，然后再按元素相加：矩阵a将复制列， 矩阵b将复制行，然后再按元素相加

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [13]:
# 索引和切片，类似python中的数组，第一个元素的索引是0，最后一个元素索引是-1； 可以指定范围以包含第一个元素和最后一个之前的元素
X[0], X[-1], X[1:3]

(tensor([0., 1., 2., 3.]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [ ]:
# 支持赋值
X[1, 2] = 9 # 将X的第二行第三列元素设为9
X[1:2, :] = 12 # 将X的第一索引行和第二索引行的所有元素设为12
X

tensor([[ 0.,  1.,  2.,  3.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.]])

In [23]:
# 引用操作，而Y = X + Y，此时会生成一个新的内存地址，将其赋值给Y，而不是在原有的Y上进行修改
Z = torch.zeros_like(X) # 创建一个与X形状相同的全零矩阵

# 执行原地操作非常简单。 我们可以使用切片表示法将操作的结果分配给先前分配的数组，例如Y[:] = <expression>
# print('Z:', Z)
Z[:] = X # 将X的所有元素赋值到Z，而非持有相同的引用
print('Z:', Z)
print(X==Z) # 验证X和Z是否相等
print('id(X):', id(X), 'id(Z):', id(Z)) # 查看X和Z的内存地址，两者的地址并不同，说明是元素的复制，而不是引用
print(torch.ones_like(Z)) # 创建一个与Z形状相同的全1矩阵

Z: tensor([[ 0.,  1.,  2.,  3.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
id(X): 13203558608 id(Z): 6440494448
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [19]:
# 或者这样写 
before = id(Y) # id函数返回变量的内存地址
Y += X # 复合运算符会改变Y的值
id(Y) == before # True，内存地址没有变

True

In [19]:
import numpy as np # NumPy是Python中一个非常流行的科学计算库。 它提供了一个强大的N维数组对象ndarray

# torch张量和numpy数组将共享它们的底层内存，就地操作更改一个张量也会同时更改另一个张量
A = X.numpy() # 将一个torch张量转换成一个numpy数组
B = torch.from_numpy(A) # 将一个numpy数组转换成一个torch张量
# 元素比对
np.array_equal(A, B) # True，A和B的元素完全相同
print(id(A), id(B)) # 查看A和B的内存地址
print(A)

13203569232 13203567440
[[ 0.  1.  2.  3.]
 [12. 12. 12. 12.]
 [12. 12. 12. 12.]]


In [ ]:
A[0] = 100 # 将A的第一个元素设为100（如果第一个元素是一个向量则将整个向量设为100）
A,B

(array([[100., 100., 100., 100.],
        [  4.,   5.,   9.,   7.],
        [ 12.,  12.,  12.,  12.]], dtype=float32),
 tensor([[100., 100., 100., 100.],
         [  4.,   5.,   9.,   7.],
         [ 12.,  12.,  12.,  12.]]))

In [ ]:
a = torch.tensor([3.5]) # 创建一个一维向量的张量
print(a, a.item(), float(a), int(a)) # item将张量转换成一个Python数值

# 创建一个标量张量
print(torch.tensor(2))

tensor([3.5000]) 3.5 3.5 3
tensor(2)


In [33]:
torch.tensor([[[1,2,3],[1,1,1]]]) + torch.tensor([1,2,3])

tensor([[[2, 4, 6],
         [2, 3, 4]]])