In [1]:
%matplotlib inline
import torch

In [ ]:
from torch.distributions import multinomial
fair_probs = torch.ones(6) / 6
fair_probs

# 离散概率采样
multinomial.Multinomial(10, fair_probs).sample()

tensor([1., 1., 3., 2., 2., 1.])

In [9]:
# 硬币的公平性
multinomial.Multinomial(10, torch.tensor([0.5, 0.5])).sample()

tensor([4., 6.])

In [15]:
# 采样1000次
multinomial.Multinomial(1000, fair_probs).sample()/1000

tensor([0.1690, 0.1780, 0.1500, 0.1610, 0.1790, 0.1630])

In [2]:
%pip install import-ipynb

Note: you may need to restart the kernel to use updated packages.


ImportError: attempted relative import with no known parent package